"""add shop_id to voucher

Revision ID: 010828320975
Revises: e566b4974b95
Create Date: 2026-03-12 21:37:01.100053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '010828320975'
down_revision = 'e566b4974b95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flash_sales', schema=None) as batch_op:
        batch_op.alter_column('discount_percent',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Integer(),
               existing_nullable=False)

    with op.batch_alter_table('vouchers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shop_id', sa.BigInteger(), nullable=False))
        batch_op.drop_constraint(batch_op.f('vouchers_code_key'), type_='unique')
        batch_op.create_foreign_key(None, 'shops', ['shop_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vouchers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_unique_constraint(batch_op.f('vouchers_code_key'), ['code'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('shop_id')

    with op.batch_alter_table('flash_sales', schema=None) as batch_op:
        batch_op.alter_column('discount_percent',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=False)

    # ### end Alembic commands ###
