"""update tables

Revision ID: 0d38f3b6dace
Revises: 5d8aad89768e
Create Date: 2026-03-06 09:45:33.613775

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0d38f3b6dace'
down_revision = '5d8aad89768e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False))
        batch_op.alter_column('order_id',
               existing_type=sa.BIGINT(),
               nullable=False)
        batch_op.alter_column('product_id',
               existing_type=sa.BIGINT(),
               nullable=False)
        batch_op.alter_column('price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
        batch_op.alter_column('quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_order_items_order_id'), ['order_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('order_items_order_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'orders', ['order_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('order_tracking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_code', sa.String(length=30), nullable=False))
        batch_op.alter_column(
       'status',
       existing_type=sa.VARCHAR(length=30),
       type_=sa.Enum('PENDING', 'CONFIRMED', 'PREPARING', 'SHIPPING', 'DELIVERED', 'CANCELLED', name='order_status'),
       existing_nullable=False,
    postgresql_using="status::order_status"
)
        batch_op.create_index(batch_op.f('ix_order_tracking_order_code'), ['order_code'], unique=True)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.BIGINT(),
               nullable=False)
        batch_op.alter_column('total_price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('pending', 'preparing', 'shipping', 'delivered', 'cancelled', name='order_status'),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_orders_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('order_id',
               existing_type=sa.BIGINT(),
               nullable=False)
        batch_op.alter_column('method',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
        batch_op.alter_column('amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_payments_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_status'), ['status'], unique=False)
        batch_op.create_unique_constraint(None, ['transaction_code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_index(batch_op.f('ix_payments_status'))
        batch_op.drop_index(batch_op.f('ix_payments_order_id'))
        batch_op.alter_column('amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
        batch_op.alter_column('method',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
        batch_op.alter_column('order_id',
               existing_type=sa.BIGINT(),
               nullable=True)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_user_id'))
        batch_op.drop_index(batch_op.f('ix_orders_status'))
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('pending', 'preparing', 'shipping', 'delivered', 'cancelled', name='order_status'),
               nullable=True)
        batch_op.alter_column('total_price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.BIGINT(),
               nullable=True)

    with op.batch_alter_table('order_tracking', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_tracking_order_code'))
        batch_op.alter_column('status',
               existing_type=sa.Enum('PENDING', 'CONFIRMED', 'PREPARING', 'SHIPPING', 'DELIVERED', 'CANCELLED', name='order_status'),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
        batch_op.drop_column('order_code')

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('order_items_order_id_fkey'), 'orders', ['order_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_order_items_order_id'))
        batch_op.alter_column('quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
        batch_op.alter_column('product_id',
               existing_type=sa.BIGINT(),
               nullable=True)
        batch_op.alter_column('order_id',
               existing_type=sa.BIGINT(),
               nullable=True)
        batch_op.drop_column('subtotal')

    op.create_table('phase1_reviews',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name=op.f('ck_phase1_review_rating')),
    sa.ForeignKeyConstraint(['product_id'], ['phase1_products.id'], name=op.f('phase1_reviews_product_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('phase1_reviews_pkey'))
    )
    with op.batch_alter_table('phase1_reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_phase1_reviews_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_phase1_reviews_product_id'), ['product_id'], unique=False)

    op.create_table('phase1_product_images',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('image_url', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['phase1_products.id'], name=op.f('phase1_product_images_product_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('phase1_product_images_pkey'))
    )
    with op.batch_alter_table('phase1_product_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_phase1_product_images_product_id'), ['product_id'], unique=False)

    op.create_table('phase1_products',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('slug', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('price', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('stock_quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('thumbnail', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('phase1_products_pkey'))
    )
    with op.batch_alter_table('phase1_products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_phase1_products_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_phase1_products_category_id'), ['category_id'], unique=False)

    # ### end Alembic commands ###
