"""expand otp_code length

Revision ID: 2f08041d1158
Revises: 
Create Date: 2026-03-02 21:22:40.316956

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2f08041d1158'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('otp_codes', schema=None) as batch_op:
        batch_op.alter_column('otp_code',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('type',
               existing_type=postgresql.ENUM('email', 'sms', name='otp_type'),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.alter_column('expired_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('is_used',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('failed_attempts',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_index('idx_otp_expired', ['expired_at'], unique=False)
        batch_op.create_index('idx_otp_user_type_used', ['user_id', 'type', 'is_used'], unique=False)
        batch_op.create_index(batch_op.f('ix_otp_codes_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('otp_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_otp_codes_user_id'))
        batch_op.drop_index('idx_otp_user_type_used')
        batch_op.drop_index('idx_otp_expired')
        batch_op.alter_column('failed_attempts',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('is_used',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('expired_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
        batch_op.alter_column('type',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('email', 'sms', name='otp_type'),
               existing_nullable=False)
        batch_op.alter_column('otp_code',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###
