"""add is_seller column

Revision ID: 41bf14fe284a
Revises: fd941695ea87
Create Date: 2026-03-06 22:53:46.935946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41bf14fe284a'
down_revision = 'fd941695ea87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shops', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pickup_address', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('contact_email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('contact_phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('legal_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('legal_name', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('tax_code', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('tax_address', sa.Text(), nullable=True))

        batch_op.add_column(sa.Column(
            'onboarding_step',
            sa.Integer(),
            nullable=False,
            server_default='0'
        ))

        batch_op.add_column(sa.Column(
            'onboarding_completed',
            sa.Boolean(),
            nullable=False,
            server_default='false'
        ))

        batch_op.add_column(sa.Column(
            'shipping_pickup_point',
            sa.Boolean(),
            nullable=True
        ))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column(
            'is_seller',
            sa.Boolean(),
            nullable=False,
            server_default='false'
        ))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_seller')

    with op.batch_alter_table('shops', schema=None) as batch_op:
        batch_op.drop_column('shipping_pickup_point')
        batch_op.drop_column('onboarding_completed')
        batch_op.drop_column('onboarding_step')
        batch_op.drop_column('tax_address')
        batch_op.drop_column('tax_code')
        batch_op.drop_column('legal_name')
        batch_op.drop_column('legal_id')
        batch_op.drop_column('contact_phone')
        batch_op.drop_column('contact_email')
        batch_op.drop_column('pickup_address')

    # ### end Alembic commands ###
