"""refactor product schema

Revision ID: 4e7ad61e46fa
Revises: 00ee557e55bf
Create Date: 2026-03-03 21:22:00.582040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e7ad61e46fa'
down_revision = '00ee557e55bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phase1_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('stock_quantity', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('thumbnail', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('phase1_products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_phase1_products_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_phase1_products_slug'), ['slug'], unique=True)

    op.create_table('phase1_product_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['phase1_products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('phase1_product_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_phase1_product_images_product_id'), ['product_id'], unique=False)

    op.create_table('phase1_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name='ck_phase1_review_rating'),
    sa.ForeignKeyConstraint(['product_id'], ['phase1_products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('phase1_reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_phase1_reviews_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_phase1_reviews_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phase1_reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_phase1_reviews_user_id'))
        batch_op.drop_index(batch_op.f('ix_phase1_reviews_product_id'))

    op.drop_table('phase1_reviews')
    with op.batch_alter_table('phase1_product_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_phase1_product_images_product_id'))

    op.drop_table('phase1_product_images')
    with op.batch_alter_table('phase1_products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_phase1_products_slug'))
        batch_op.drop_index(batch_op.f('ix_phase1_products_category_id'))

    op.drop_table('phase1_products')
    # ### end Alembic commands ###
