"""refactor product schema

Revision ID: 5d8aad89768e
Revises: 4e7ad61e46fa
Create Date: 2026-03-03 22:02:20.992331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d8aad89768e'
down_revision = '4e7ad61e46fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('stock_quantity', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('category_id', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('thumbnail', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
        batch_op.create_index(batch_op.f('ix_products_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_slug'), ['slug'], unique=True)
        batch_op.create_foreign_key(None, 'categories', ['category_id'], ['id'])
        batch_op.drop_column('stock')

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.alter_column('product_id',
               existing_type=sa.BIGINT(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_reviews_product_id'), ['product_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('reviews_product_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'products', ['product_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('reviews_product_id_fkey'), 'products', ['product_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_reviews_product_id'))
        batch_op.alter_column('product_id',
               existing_type=sa.BIGINT(),
               nullable=True)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stock', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_products_slug'))
        batch_op.drop_index(batch_op.f('ix_products_category_id'))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('thumbnail')
        batch_op.drop_column('category_id')
        batch_op.drop_column('stock_quantity')
        batch_op.drop_column('slug')

    # ### end Alembic commands ###
