"""refactor product variant system

Revision ID: 61b6f1b78bb3
Revises: 2dd5df952720
Create Date: 2026-03-08 17:13:27.661795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61b6f1b78bb3'
down_revision = '2dd5df952720'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('variant_attributes',
    sa.Column('variant_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=100), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_variants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sku', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('image_url', sa.String(length=500), nullable=True))
        batch_op.alter_column('price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
        batch_op.drop_index(batch_op.f('idx_product_variants_product_id'))
        batch_op.create_unique_constraint(None, ['sku'])
        batch_op.drop_column('size')
        batch_op.drop_column('color')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_category_id'))
        batch_op.drop_constraint(batch_op.f('products_category_id_fkey'), type_='foreignkey')
        batch_op.drop_column('price')
        batch_op.drop_column('qr_code')
        batch_op.drop_column('category_id')
        batch_op.drop_column('stock_quantity')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stock_quantity', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('category_id', sa.BIGINT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('qr_code', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('price', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('products_category_id_fkey'), 'categories', ['category_id'], ['id'])
        batch_op.create_index(batch_op.f('ix_products_category_id'), ['category_id'], unique=False)

    with op.batch_alter_table('product_variants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('size', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index(batch_op.f('idx_product_variants_product_id'), ['product_id'], unique=False)
        batch_op.alter_column('price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
        batch_op.drop_column('image_url')
        batch_op.drop_column('sku')

    op.drop_table('variant_attributes')
    # ### end Alembic commands ###
