"""fix timezone

Revision ID: 8897eb48e61c
Revises: 61b6f1b78bb3
Create Date: 2026-03-10 20:19:52.475045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8897eb48e61c'
down_revision = '61b6f1b78bb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_variants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weight', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('length', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('width', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('height', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('shipping_fast_fee', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('shipping_same_day_fee', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('shipping_express_fee', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('shipping_pickup_fee', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('shipping_bulky_fee', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_variants', schema=None) as batch_op:
        batch_op.drop_column('shipping_bulky_fee')
        batch_op.drop_column('shipping_pickup_fee')
        batch_op.drop_column('shipping_express_fee')
        batch_op.drop_column('shipping_same_day_fee')
        batch_op.drop_column('shipping_fast_fee')
        batch_op.drop_column('height')
        batch_op.drop_column('width')
        batch_op.drop_column('length')
        batch_op.drop_column('weight')

    # ### end Alembic commands ###
