"""fix timezonee

Revision ID: e566b4974b95
Revises: 8897eb48e61c
Create Date: 2026-03-11 22:17:27.272069

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e566b4974b95'
down_revision = '8897eb48e61c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promotions',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('variant_id', sa.BigInteger(), nullable=False),
    sa.Column('discount_percent', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('flash_sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('variant_id', sa.BigInteger(), nullable=False))
        batch_op.add_column(sa.Column('discount_percent', sa.Numeric(precision=12, scale=2), nullable=False))
        batch_op.alter_column('stock_limit',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('flash_sales_product_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'product_variants', ['variant_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('product_id')
        batch_op.drop_column('discount_price')

    with op.batch_alter_table('vouchers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('min_order_value', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('usage_limit', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('used_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('start_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('end_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.alter_column('discount_type',
               existing_type=postgresql.ENUM('PERCENT', 'FIXED', name='discount_type'),
               type_=sa.String(length=20),
               nullable=True)
        batch_op.alter_column('discount_value',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Integer(),
               nullable=True)
        batch_op.drop_column('quantity')
        batch_op.drop_column('min_order_amount')
        batch_op.drop_column('max_discount')
        batch_op.drop_column('used_quantity')
        batch_op.drop_column('expired_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vouchers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expired_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('used_quantity', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('max_discount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('min_order_amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.alter_column('discount_value',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
        batch_op.alter_column('discount_type',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('PERCENT', 'FIXED', name='discount_type'),
               nullable=False)
        batch_op.drop_column('is_active')
        batch_op.drop_column('end_time')
        batch_op.drop_column('start_time')
        batch_op.drop_column('used_count')
        batch_op.drop_column('usage_limit')
        batch_op.drop_column('min_order_value')
        batch_op.drop_column('name')

    with op.batch_alter_table('flash_sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discount_price', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('product_id', sa.BIGINT(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('flash_sales_product_id_fkey'), 'products', ['product_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('stock_limit',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('discount_percent')
        batch_op.drop_column('variant_id')

    op.drop_table('promotions')
    # ### end Alembic commands ###
