"""fix timezone

Revision ID: fd941695ea87
Revises: 0d38f3b6dace
Create Date: 2026-03-06 16:29:29.555463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd941695ea87'
down_revision = '0d38f3b6dace'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shops', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shipping_fast', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('shipping_same_day', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('shipping_express', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('shipping_self_delivery', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('shipping_bulky', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('shipping_configured', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shops', schema=None) as batch_op:
        batch_op.drop_column('shipping_configured')
        batch_op.drop_column('shipping_bulky')
        batch_op.drop_column('shipping_self_delivery')
        batch_op.drop_column('shipping_express')
        batch_op.drop_column('shipping_same_day')
        batch_op.drop_column('shipping_fast')

    # ### end Alembic commands ###
